on:
  workflow_dispatch:
  push:
    branches:
      - main

name: "Bump v1"

permissions:
  contents: write

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
