on:
  workflow_dispatch:
  push:
    branches:
      - main

name: "Bump v1"

permissions:
  contents: write

jobs:
  update_version:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
