on:
  workflow_dispatch:
  push:
    branches:
      - main

name: "Bump v1"

jobs:
  update_version:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # - name: Bump dev version
    #   uses: DanChaltiel/actions/bump-dev-version@v1
    #   with:
    #     create-tag: 'true'
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::desc

    - name: Increment dev version
      id: vars
      run: |
        invisible(desc::desc_bump_version("dev"))
        new_version = desc::desc_get_version()
        cat(sprintf("PKG_NEW_VERSION=%s\n", new_version),
            file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        message("Setting PKG_NEW_VERSION to ", new_version)
      shell: Rscript {0}

    - name: Commit the version change
      run: |
        git add DESCRIPTION
        git commit -m "Update dev version to ${{ env.PKG_NEW_VERSION }} (Github Actions)" -m "[skip ci]"
        git push

    # - name: Commit the version change
    #   if: inputs.create-tag == 'false'
    #   uses: EndBug/add-and-commit@v9
    #   with:
    #     default_author: github_actions
    #     message: 'Update dev version (Github Actions)'
    #
    #
    # - name: Commit the version change and add tag
    #   if: inputs.create-tag != 'false'
    #   uses: EndBug/add-and-commit@v9
    #   with:
    #     default_author: github_actions
    #     tag: 'v${{ env.PKG_NEW_VERSION }} --force'
    #     message: 'Update dev version (Github Actions)'
