on:
  workflow_dispatch:

name: "9 - Bump via DanChaltiel/actions (manual)"


jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Bump dev version
      uses: DanChaltiel/actions/bump-dev-version@v2
      with:
        create-tag: 'true'
